// =============================================================================
// Project: FALX V2
// Lead Architect & Owner: FT-1
// Description: Event bus tests (control-plane/internal/events/bus_test.go).
// =============================================================================

package events

import (
	"sync"
	"sync/atomic"
	"testing"
	"time"
)

func TestPublishSubscribe(t *testing.T) {
	bus := NewBus()
	sub := bus.Subscribe("test-sub", 32, TopicIPBlocked)

	bus.Publish(IPBlockedEvent("1.2.3.4", "actor", "test", 3600))

	select {
	case ev := <-sub.Ch:
		if ev.Topic != TopicIPBlocked {
			t.Errorf("wrong topic: %s", ev.Topic)
		}
		if ev.Meta["src_ip"] != "1.2.3.4" {
			t.Errorf("wrong src_ip: %s", ev.Meta["src_ip"])
		}
	case <-time.After(100 * time.Millisecond):
		t.Fatal("timeout waiting for event")
	}
}

func TestMultipleSubscribers(t *testing.T) {
	bus := NewBus()
	sub1 := bus.Subscribe("sub1", 32, TopicIPBlocked)
	sub2 := bus.Subscribe("sub2", 32, TopicIPBlocked)
	sub3 := bus.Subscribe("sub3", 32, TopicCircuitOpen) // Different topic

	bus.Publish(IPBlockedEvent("5.5.5.5", "actor", "reason", 0))

	// sub1 and sub2 should receive
	for _, sub := range []*Subscriber{sub1, sub2} {
		select {
		case ev := <-sub.Ch:
			if ev.Topic != TopicIPBlocked {
				t.Errorf("subscriber %s: wrong topic", sub.ID)
			}
		case <-time.After(100 * time.Millisecond):
			t.Errorf("subscriber %s: timeout", sub.ID)
		}
	}

	// sub3 should NOT receive (different topic)
	select {
	case ev := <-sub3.Ch:
		t.Errorf("sub3 should not receive IPBlocked, got: %s", ev.Topic)
	case <-time.After(50 * time.Millisecond):
		// Correct: no event
	}
}

func TestEventIDAutoGenerated(t *testing.T) {
	bus := NewBus()
	sub := bus.Subscribe("id-test", 32, TopicCircuitOpen)

	// Publish event without ID
	bus.Publish(Event{Topic: TopicCircuitOpen, Severity: SeverityCritical})

	select {
	case ev := <-sub.Ch:
		if ev.ID == "" {
			t.Error("event ID should be auto-generated")
		}
		if ev.Timestamp.IsZero() {
			t.Error("event timestamp should be auto-set")
		}
	case <-time.After(100 * time.Millisecond):
		t.Fatal("timeout")
	}
}

func TestDropOnFullChannel(t *testing.T) {
	bus := NewBus()
	// Buffer of 2 events
	sub := bus.Subscribe("slow-sub", 2, TopicThreatAlert)

	// Publish 10 events into a buffer of 2 — 8 should be dropped
	for i := 0; i < 10; i++ {
		bus.Publish(ThreatAlertEvent("1.1.1.1", "scan", "medium", 0.7))
	}

	dropped := bus.DropCount()
	if dropped < 8 {
		t.Errorf("expected >= 8 drops, got %d", dropped)
	}

	// Channel should have exactly 2 events
	count := 0
	for {
		select {
		case <-sub.Ch:
			count++
		default:
			goto done
		}
	}
done:
	if count != 2 {
		t.Errorf("expected 2 events in buffer, got %d", count)
	}
}

func TestUnsubscribe(t *testing.T) {
	bus := NewBus()
	sub := bus.Subscribe("unsub-test", 32, TopicAuthFailed)
	bus.Unsubscribe(sub)

	// After unsubscribe, channel is closed
	_, open := <-sub.Ch
	if open {
		t.Error("channel should be closed after unsubscribe")
	}
}

func TestConcurrentPublish(t *testing.T) {
	bus := NewBus()
	sub := bus.Subscribe("concurrent", 1024, TopicIPBlocked)

	const goroutines = 100
	var published atomic.Int64
	var wg sync.WaitGroup
	wg.Add(goroutines)

	for i := 0; i < goroutines; i++ {
		go func() {
			defer wg.Done()
			bus.Publish(IPBlockedEvent("2.2.2.2", "actor", "concurrent-test", 60))
			published.Add(1)
		}()
	}
	wg.Wait()

	// Drain channel
	received := 0
	deadline := time.Now().Add(500 * time.Millisecond)
	for time.Now().Before(deadline) {
		select {
		case <-sub.Ch:
			received++
		default:
			time.Sleep(10 * time.Millisecond)
		}
	}

	total := received + int(bus.DropCount())
	if total != goroutines {
		t.Errorf("published=%d, received=%d, dropped=%d, total=%d (should be %d)",
			published.Load(), received, bus.DropCount(), total, goroutines)
	}
}

func BenchmarkPublish(b *testing.B) {
	bus  := NewBus()
	sub  := bus.Subscribe("bench-sub", 65536, TopicIPBlocked)
	go func() { for range sub.Ch {} }() // Drain

	ev := IPBlockedEvent("1.2.3.4", "bench", "test", 60)
	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		bus.Publish(ev)
	}
}

func BenchmarkPublishFanOut_10Subscribers(b *testing.B) {
	bus := NewBus()
	for i := 0; i < 10; i++ {
		sub := bus.Subscribe("sub", 65536, TopicIPBlocked)
		go func() { for range sub.Ch {} }()
	}

	ev := IPBlockedEvent("1.2.3.4", "bench", "test", 60)
	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		bus.Publish(ev)
	}
}
