#!/usr/bin/env bash
# =============================================================================
# Project: FALX V2  |  Lead Architect & Owner: FT-1
# Description: falx-install — the one-shot, zero-touch installer.
#
#   Runs end-to-end with a SINGLE command and NO interaction:
#     1. Installs every build dependency (Go, Python3, Rust + bpf-linker,
#        clang/llvm/libbpf, kernel headers, sqlite, make, …).
#     2. Mounts the BPF filesystem (and persists it in /etc/fstab).
#     3. Builds all components  (make dev → eBPF + falx-user + falxd + falx-soc).
#     4. Links the 4 global commands into /usr/local/bin:
#          falx-install · falx-on · falx-off · falx-remove
#
#   Usage:
#     sudo bash scripts/falx-install.sh          # full install + build + link
#     sudo bash scripts/falx-install.sh --no-deps  # skip apt/toolchain step
#     sudo bash scripts/falx-install.sh --link-only # only (re)link the 4 commands
#
#   After it finishes, `falx-on` / `falx-off` / `falx-remove` / `falx-install`
#   work from ANY directory.
# =============================================================================

set -uo pipefail

# ─── Colors ───────────────────────────────────────────────────────────────────
R='\033[0;31m' G='\033[0;32m' Y='\033[1;33m' C='\033[0;36m' M='\033[0;35m'
B='\033[1m' N='\033[0m'
step()   { echo -e "\n${B}${C}  ══════  $*  ══════${N}"; }
info()   { echo -e "  ${C}[INFO]${N}   $*"; }
ok()     { echo -e "  ${G}[  OK ]${N}  $*"; }
warn()   { echo -e "  ${Y}[ WARN]${N}  $*"; }
fail()   { echo -e "  ${R}[ FAIL]${N}  $*"; exit 1; }

[[ $EUID -ne 0 ]] && fail "Run as root:  sudo bash scripts/falx-install.sh"

# ─── Args ─────────────────────────────────────────────────────────────────────
NO_DEPS=false
LINK_ONLY=false
for a in "$@"; do case "$a" in
    --no-deps)   NO_DEPS=true ;;
    --link-only) LINK_ONLY=true ;;
    *) fail "Unknown option: $a" ;;
esac done

# ─── Resolve repo root ────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
BIN_DIR="/usr/local/bin"

echo -e "\n${B}${M}  ╔══════════════════════════════════════════════════════════╗${N}"
echo -e "${B}${M}  ║   ⚡  FALX V2  —  Installer  (Lead Architect: FT-1)       ║${N}"
echo -e "${B}${M}  ╚══════════════════════════════════════════════════════════╝${N}"
echo -e "  repo: ${REPO_ROOT}"

# ─── link_commands: wire the 4 global commands ───────────────────────────────
link_commands() {
    step "Linking global commands"
    local cmds=(falx-install falx-on falx-off falx-remove)
    for c in "${cmds[@]}"; do
        local target="${REPO_ROOT}/scripts/${c}.sh"
        [[ -f "$target" ]] || { warn "missing ${target} — skipping ${c}"; continue; }
        cat > "${BIN_DIR}/${c}" <<EOF
#!/usr/bin/env bash
# FALX V2 global command — generated by falx-install. Re-run the installer if
# you relocate the repository.
exec sudo bash "${REPO_ROOT}/scripts/${c}.sh" "\$@"
EOF
        chmod 755 "${BIN_DIR}/${c}"
        ok "${B}${c}${N} → ${target}"
    done
}

if [[ "$LINK_ONLY" == true ]]; then
    link_commands
    echo -e "\n${G}${B}  Commands linked.${N}\n"
    exit 0
fi

# ─── 1. Dependencies ──────────────────────────────────────────────────────────
need_install=false
command -v go      &>/dev/null || need_install=true
command -v cargo   &>/dev/null || need_install=true
command -v clang   &>/dev/null || need_install=true
command -v python3 &>/dev/null || need_install=true

if [[ "$NO_DEPS" == false && "$need_install" == true ]]; then
    step "Installing dependencies  (first run: 5–15 min)"
    export DEBIAN_FRONTEND=noninteractive

    info "Installing system packages via apt…"
    apt-get update -qq || warn "apt-get update reported issues — continuing"
    apt-get install -y --no-install-recommends \
        build-essential curl wget git pkg-config make \
        llvm clang libelf-dev libbpf-dev \
        "linux-headers-$(uname -r)" \
        linux-tools-common "linux-tools-$(uname -r)" \
        sqlite3 libsqlite3-dev \
        python3 \
        ca-certificates jq lsb-release \
        2>/dev/null || warn "Some apt packages failed — verifying critical tools below"
    ok "System packages processed"

    # ── Rust nightly + bpf-linker (eBPF kernel + falx-user loader) ────────────
    export CARGO_HOME="${CARGO_HOME:-/root/.cargo}"
    export RUSTUP_HOME="${RUSTUP_HOME:-/root/.rustup}"
    if ! command -v cargo &>/dev/null; then
        info "Installing Rust (nightly) toolchain…"
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
            | sh -s -- -y --profile minimal --default-toolchain nightly --no-modify-path 2>&1 | tail -3
    fi
    [[ -f "$CARGO_HOME/env" ]] && source "$CARGO_HOME/env" || true
    rustup component add rust-src --toolchain nightly 2>/dev/null || true
    command -v bpf-linker &>/dev/null || cargo install bpf-linker 2>/dev/null || true
    ok "Rust toolchain ready: $(rustc --version 2>/dev/null || echo '?')"

    # ── Go 1.23.4 (control-plane + soc-backend) ───────────────────────────────
    GO_WANT="1.23.4"
    need_go=false
    if ! command -v go &>/dev/null; then
        need_go=true
    else
        cur=$(go version | awk '{print $3}' | tr -d 'go')
        [[ "$(printf '%s\n' 1.23 "$cur" | sort -V | head -1)" != "1.23" ]] && need_go=true || true
    fi
    if [[ "$need_go" == true ]]; then
        info "Installing Go ${GO_WANT}…"
        GO_ARCH=$(dpkg --print-architecture 2>/dev/null || uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
        GO_TGZ="go${GO_WANT}.linux-${GO_ARCH}.tar.gz"
        if wget -q "https://golang.org/dl/${GO_TGZ}" -O "/tmp/${GO_TGZ}"; then
            rm -rf /usr/local/go && tar -C /usr/local -xzf "/tmp/${GO_TGZ}" && rm -f "/tmp/${GO_TGZ}"
            ln -sf /usr/local/go/bin/go    /usr/local/bin/go
            ln -sf /usr/local/go/bin/gofmt /usr/local/bin/gofmt
            ok "Go ${GO_WANT} installed"
        else
            warn "Go download failed — install Go ≥ 1.23 manually, then re-run with --no-deps"
        fi
    else
        ok "Go present: $(go version)"
    fi
else
    info "Skipping dependency step (--no-deps or all tools already present)"
fi

# Make toolchains visible to this shell for the build step.
export PATH="/usr/local/go/bin:/usr/local/bin:${PATH}"
export CARGO_HOME="${CARGO_HOME:-/root/.cargo}"
export RUSTUP_HOME="${RUSTUP_HOME:-/root/.rustup}"
[[ -f "$CARGO_HOME/env" ]] && source "$CARGO_HOME/env" || true

# ── Verify critical tooling before building ──────────────────────────────────
for t in go cargo clang python3 make; do
    command -v "$t" &>/dev/null || fail "Required tool '$t' missing after install. Fix it, then re-run."
done

# ─── 2. BPF filesystem ────────────────────────────────────────────────────────
step "BPF filesystem"
if ! mountpoint -q /sys/fs/bpf 2>/dev/null; then
    mkdir -p /sys/fs/bpf
    mount -t bpf bpf /sys/fs/bpf && ok "Mounted bpffs at /sys/fs/bpf" || warn "Could not mount bpffs now"
else
    ok "bpffs already mounted"
fi
grep -q '/sys/fs/bpf' /etc/fstab 2>/dev/null || echo "bpf /sys/fs/bpf bpf defaults 0 0" >> /etc/fstab

# ─── 3. Build all components ──────────────────────────────────────────────────
step "Building FALX V2  (eBPF · falx-user · falxd · falx-soc)"
cd "$REPO_ROOT"
if make dev; then
    ok "Build complete"
else
    fail "Build failed. Scroll up for the first error, fix it, then re-run falx-install."
fi

# ── Verify the binaries the runtime needs ────────────────────────────────────
MISSING=""
[[ -x "${REPO_ROOT}/dist/falxd"          ]] || MISSING+=" falxd"
[[ -x "${REPO_ROOT}/dist/falx-soc"       ]] || MISSING+=" falx-soc"
[[ -x "${REPO_ROOT}/build/user/falx-user" || -x "${REPO_ROOT}/dist/falx-user" ]] || MISSING+=" falx-user"
[[ -n "$MISSING" ]] && warn "Build finished but these binaries are missing:${MISSING}" \
                    || ok "All runtime binaries present (falxd, falx-soc, falx-user)"

# ─── 4. Link the 4 global commands ────────────────────────────────────────────
link_commands

# ─── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "${B}${G}  ╔══════════════════════════════════════════════════════════╗${N}"
echo -e "${B}${G}  ║   ✓  FALX V2 installed — 4 commands ready system-wide     ║${N}"
echo -e "${B}${G}  ╚══════════════════════════════════════════════════════════╝${N}"
echo -e "    ${G}falx-on${N}       تشغيل المنظومة + طباعة كود 2FA اللحظي للأدمن"
echo -e "    ${G}falx-off${N}      إيقاف فوري + نزع XDP + تنظيف + استعادة الإنترنت"
echo -e "    ${G}falx-install${N}  إعادة التثبيت/البناء في أي وقت"
echo -e "    ${G}falx-remove${N}   إزالة كاملة وإرجاع السيرفر نظيفاً"
echo ""
echo -e "  ابدأ الآن:  ${B}falx-on${N}\n"
